### PR TITLE
Changed @RuntimePermissions to TypeMirror-based class validation

### LINKED ISSUE #14: Can't use with AndroidAnnotations
Because they use _ ends with classes actually.

### PR DESCRIPTION
**Pull request by aurae**
* rather than checking if an annotated class ends in "Activity" or "Fragment", its type is compared to `android.app.Activity` and `android.support.v4.app.Fragment` in order to find their ClassType
* this fixes #14 ("Can't use with AndroidAnnotations")

### CODE REVIEW

**Comment by aurae** [comment]
This PR causes a conflict in `RuntimePermissionsAnnotatedElement.java`, because its constructor changed to allow for the class type check to work.

**Comment by hotchemi** [comment]
Awesome!

**Comment by aurae** [comment]
I figured that it would make sense to implement this, even though the Kotlin version already fixed this. Depending on when v2 will be out, this can fix some issues in the meantime!

**Comment by hotchemi** [comment]
I'm gonna check it, just a minute:-)

**Comment by hotchemi** [comment]
@aurae Sorry for the late. Almost everything is LGTM but I wanna fix something on master branch. So could u solve the conflict and ready for merge?

**Comment by hotchemi** [comment]
OK, I'm gonna copy this feature to this repo.

**Comment by hotchemi** [comment]
I merged it to #29. So I'm gonna close this pr.

**Pull request closed without merging**
