### PR TITLE
Add separate module for annotations

### PR DESCRIPTION
**Pull request by hvisser**
This adds a separate module for the annotations so that the processor no longer depends on the Android library project. This is not allowed in Android builds and gives a warning. Updated `android-apt` to 1.7 and updated the sample project dependency to `provided`. Normally `apt` should work as well, but I guess that's a bug in `android-apt` that I have to fix ;)

I'm not 100% sure if publishing to Maven works correctly with the extra module addition.

### CODE REVIEW

**Comment by hotchemi** [comment]
Wow great! This is actually I've been thinking.
But I'd like to ask you an one point,

When it comes to separate to annotations and "core" module, user have to write 3 dependencies definition in their build.gradle, I think it's not major style, I mean some famous library(like butterknife, auto-parcel, deeplinkdispatch) give two dependency, core and "processor".

How do you think about of it?

**Comment by hotchemi** [comment]
There is no problem in changes.

**Comment by hvisser** [comment]
You can have two dependencies if you have normal jar projects, like `auto-parcel` for example. If you have an `android-library` project, the processor cannot have a dependency on that since `javac` does not know about that on the class path. Butterknife only has one jar with everything packed into that, but that's not as nice, since the processor will end up in your apk file, unless you use ProGuard.

It's kind of annoying, but there's basically a world for the annotation processor at compile time and one for the Android code at run time.

**Comment by hotchemi** [comment]
I see. But actually I wanna check everything goes well before merge it to master branch. So could you send a pull request to develop branch again? Anyway, I really appreciate for you contribution!

**Comment by hotchemi** [comment]
So I'm gonna close the issue.

**Comment by hvisser** [comment]
Ehm OK, the develop branch did not exist when sent you the PR, so this should still apply to that branch.

**Comment by hotchemi** [comment]
Yeah, I'm really sorry for that.

**Pull request closed without merging**
