### PR TITLE
Change to RetentionPolicy.CLASS

### PR DESCRIPTION
**Pull request by shiraji**
see #112

### CODE REVIEW

**Comment by shiraji** [comment]
@hotchemi could you reproduce this issue? I couldn't figure out why `:library:lint` fails.

**Comment by hotchemi** [comment]
Umm, ok.

**Comment by hotchemi** [comment]
library:lint didn't failed but 1 test completed, :lint:test failed on my local...

**Comment by shiraji** [comment]
Did you rerun travis ci?

**Comment by hotchemi** [comment]
Yes and ci succeeded.... :open_mouth:

**Comment by shiraji** [comment]
:fearful: scared...

What should we do for this pull request? By the way, are you ok to change `RetentionPolicy`?

**Comment by hotchemi** [comment]
I'll rerun again...
Yes, that's the only way to fix this problem for the time being...

**Comment by shiraji** [comment]
Thnaks. Hope this fix the issue

**Comment by hotchemi** [comment]
I'll test with sample module tonight and if it is ok, release new version.

**Pull request merged**
