### PR TITLE
Fix problem with @OnNeverAskAgain

### PR DESCRIPTION
**Pull request by shiraji**
see #78

### CODE REVIEW

**Comment by hotchemi** [comment]
@shiraji Thx! I've not tasted it but `Build.VERSION_CODES.M` might cause compile error when device os is under M. Right?

**Comment by shiraji** [comment]
Right. let me replace with 23.

**Comment by shiraji** [comment]
Do you want me to commit separately and after your review, squash the commits?

**Comment by shiraji** [comment]
Fixed it and squashed

**Comment by aurae** [comment]
`Build.VERSION_CODES.M` doesn't cause issues with pre-Marshmallow devices, because these constants are being provided by the SDK level used for compilation, rather than the target SDK level on the device. They get replaced by their numerical value during the compilation step

**Comment by shiraji** [comment]
I'm ready for force push, again!

Maybe I am too sleepy to think carefully. Actually, my company's app uses Build.VERSION_CODES.KITKAT to find if the running device is under 19 or not without any error report.

**Comment by hotchemi** [comment]
Oh sorry, I'm gonna test it and merge.
Anyway really appreciated for your great work!

**Comment by shiraji** [comment]
Do you want me to revert the change? I haven't push it yet.

**Comment by hotchemi** [comment]
Umm, it didn't go well...I have to investigate more.

**Comment by shiraji** [comment]
From initial [comment](https://github.com/hotchemi/PermissionsDispatcher/issues/45#issuecomment-160058769).

> App's targetSdkVersion is under 23 and device os is 6.0

I don't see any implementation for `targetSdkVersion is under 23`

`Build.VERSION.SDK_INT < 23` is for runtime. It checks device os is under 6.0. It doesn't check if its targetSdkVersion is less than 23, does it?

**Comment by hotchemi** [comment]
Exactly, I'm fixing it now!

**Pull request merged**
