### PR TITLE
Fix lint onRequestPermissionsResult

### LINKED ISSUE #124: Error:Execution failed for task ':sample:clean'
When I include PermissionsDispatcher code, my project fails to clean build with following error message: 

Error:Execution failed for task ':sample:clean'.
> Unable to delete file: C:\PermissionsDispatcher-master\PermissionsDispatcher-master\sample\build\intermediates\exploded-aar\PermissionsDispatcher-master\library\unspecified\jars\lint.jar

If I remove this PermissionDispatcher code including from build.gradle file then everything working fine.

### LINKED ISSUE #130: Entire class has warning "Generated onRequestPermissionsResult method not called"
I get my whole class underlined in red with this warning:

> "Generated onRequestPermissionsResult method not called [NeedOnRequestPermissionsResult]"

My code is fine. It compiles and runs but the editor warning keeps showing also on every class nested in a fragment or activity. Could you please fix it as I can't see my own real errors :D.

### PR DESCRIPTION
**Pull request by shiraji**
Fix #124 
Fix #130

### CODE REVIEW

**Comment by hotchemi** [comment]
Cool. Could you explain a little bit how to fix the problem?

**Comment by shiraji** [comment]
OK, to be honest, I don't know if this fix the redline problems. I got positive 2 responses from gentle developers.

What I saw from developers' reports, I was thinking, the lint has trouble with reading XxxPermissionsDispatcher class, which apt generates. I replaced Scope.JAVA_FILE to Scope.CLASS_FILE, so that the lint must check its class file not java file (and hope before lint check, apt always generate XxxPermissionsDispatcher. See now you know why I don't know if this fix the issue)

Does this answer your question?

**Comment by hotchemi** [comment]
Gotcha!

**Comment by BenoitDuffez** [comment]
Working like a charm with 2.1.2. Thanks a lot.

**Comment by shiraji** [comment]
You make me feel relieved! Thanks for your report @BenoitDuffez

**Pull request merged**
