### PR TITLE
Add target SDK version check for special permissions

### LINKED ISSUE #147: Add TargetSDK Version Judge,Please.
I use "android.permission.SYSTEM_ALERT_WINDOW" ,run on Android6.0 is very OK.

but,run on Android4.2,Occure FATAL EXCEPTION.

i guess Android4.2 SDK  no exists " android.provider.Settings.canDrawOverlays" method.

image

please add judge SDK version in PermissionDispater.

PermissionDispater is very good frame.

### PR DESCRIPTION
**Pull request by shiraji**
Close #147

### CODE REVIEW

**Comment by hotchemi** [comment]
👀

**Comment by aurae** [comment]
Your speed is breathtaking! 💨

**Comment by shiraji** [comment]
@aurae Thanks...but it's not working...

**Comment by shiraji** [comment]
```java
if (!PermissionUtils.hasSelfPermissions(target, PERMISSION_SYSTEMALERTWINDOW) && Settings.canDrawOverlays(target)) {
    target.systemAlertWindow();
}
```

And

```java
    static {
        MIN_SDK_PERMISSIONS = new SimpleArrayMap<>(8);
        MIN_SDK_PERMISSIONS.put("com.android.voicemail.permission.ADD_VOICEMAIL", 14);
        MIN_SDK_PERMISSIONS.put("android.permission.BODY_SENSORS", 20);
        MIN_SDK_PERMISSIONS.put("android.permission.READ_CALL_LOG", 16);
        MIN_SDK_PERMISSIONS.put("android.permission.READ_EXTERNAL_STORAGE", 16);
        MIN_SDK_PERMISSIONS.put("android.permission.USE_SIP", 9);
        MIN_SDK_PERMISSIONS.put("android.permission.WRITE_CALL_LOG", 16);
        MIN_SDK_PERMISSIONS.put("android.permission.SYSTEM_ALERT_WINDOW", 23);
        MIN_SDK_PERMISSIONS.put("android.permission.WRITE_SETTINGS", 23);
    }
```

**Comment by shiraji** [comment]
What I did is adding special permissions to `MIN_SDK_PERMISSIONS` so that `PermissionUtils#hasSelfPermissions` return `true` if `Build.VERSION.SDK_INT` is less than 23.

**Comment by hotchemi** [comment]
LGTM 💯

**Pull request merged**
