### PR TITLE
Modify to cache target sdk version.

### PR DESCRIPTION
**Pull request by hotchemi**
Just modify to cache targetSdkVersion to static variable.
This method might be called plural times, so it would improve perfomance.

### CODE REVIEW

**Comment by hotchemi** [comment]
Changed assignee to shiraji cuz aurae is on trip now.

**Comment by aurae** [comment]
Why is `targetSdkVersion` an `Integer` rather than a primitive?

**Comment by hotchemi** [comment]
I thought we can't check the variable is already set or not. But umm, we can check it as 0 or not right?

**Comment by hotchemi** [comment]
Fixed.

**Comment by hotchemi** [comment]
Umm, I have to choose double check pattern like Picasso...it's not clean code but we have to take care of performance...

**Comment by hotchemi** [comment]
@shiraji thoughts?

**Comment by shiraji** [comment]
Too little too late...but does it need to be `synchronized`? We can accept multiple thread accessing package info.

**Comment by hotchemi** [comment]
When it comes to package info, yes. But I don't want to getTargetSdkVersion to return -1 unexpectedly.
I'm not sure volatile is enough...

**Comment by shiraji** [comment]
OK. we can survive for the code. Let see if someone reports issue for `getTargetSdkVersion`.

**Comment by hotchemi** [comment]
@shiraji Sorry, I changed my mind and delete it...! I guess it's hardly called at the same time:D

**Comment by hotchemi** [comment]
#97 .

**Pull request merged**
